name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: docker build -t frontend ./frontend

      - name: Build Backend Docker Image
        run: docker build -t backend ./backend

      - name: Docker Compose Build
        run: docker compose build